apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata: 
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bahloulisaid/frontend:latest
        env:
        - name: API_URL
          value: http://192.168.49.2:31111
